version: '3.1'

services:
  account-management-service:
    build: ./account-management-service
    ports:
      - "9291:9291"
    depends_on:
      - mysql
      - zookeeper
      - kafka
  ledger-balance-service:
    build: ./ledger-balances-query-service
    ports:
      - "8291:8291"
    depends_on:
      - mysql
      - zookeeper
      - kafka
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
    ports:
      - "3306:3306"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
