version: '3.1'

services:
  account-management-service:
    build: ./account-management-service
    ports:
      - "9291:9291"
  ledger-balance-service:
    build: ./ledger-balances-query-service
    ports:
      - "8291:8291"

